version: "3.8"

services:
  backend:
    build: .
    container_name: scrapsavvy-backend

    ports:
      - "8080:8080"

    env_file:
      - .env

    environment:
      DB_URL: ${DB_URL}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
      RAZORPAY_KEY: ${RAZORPAY_KEY}
      RAZORPAY_SECRET: ${RAZORPAY_SECRET}
      SPRING_PROFILES_ACTIVE: prod

    restart: always
