spring.application.name=Scrap

# Database
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=604800000

# Multipart
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=50MB

# Razorpay
razorpay.key.id=${RAZORPAY_KEY}
razorpay.key.secret=${RAZORPAY_SECRET}

# Server
server.port=8080

# Logging
logging.level.root=INFO
logging.level.org.springframework.security=WARN

# Swagger
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true